### ISSUE TITLE
localhost returns `Not Found`

### ISSUE THREAD

**Issue by pavittarx** [lit/lit-element-starter-ts#23]
I have cloned this repository as is. I am following lit-element docs from here: https://lit-element.polymer-project.org/guide/start#try-out-your-project

Steps: 
1. npm run build
2. npm run serve

I have tried npm run clean, and then retried above steps. The dev server starts but it displays `Not Found`.

**Comment by snoop244** [comment]
Same here.

**Comment by premshree** [comment]
I have run into the same issue.

**Comment by premshree** [comment]
Oh, gosh, I wish this was obvious, but the problem is simply that you need to go to `http://localhost:8000/dev` :{

**Comment by rodydavis** [comment]
<img width="541" alt="Screen Shot 2020-08-25 at 10 31 26 AM" src="https://user-images.githubusercontent.com/31253215/91207817-383e4080-e6be-11ea-91d6-eb0307250554.png">

Yep same. I will update the docs If i can

**Comment by illepic** [comment]
@premshree saved me a late night!

**Comment by AndrewJakubowicz** [comment]
This has been addressed with https://github.com/lit/lit-element-starter-ts/commit/43c1dfb1c9444ca621aced60640e5bd8dfa36182. `npm run serve` will now guide you to where your component is defined.
Thank you!
